version: '3'
services:
  activity-service: 
    build: .
    container_name: usermanager-service
    ports:
      - 80:80

  mysql:
    image: mysql
    container_name: usermanager_database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fuper
      MYSQL_DATABASE: usermanager_db
    volumes:
      - ./mysql_db_data:/var/lib/mysql
      - ./entry:/docker-entrypoint-initdb.d/ 
